name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install node modules
        run: |
          yarn install

      - run: yarn test-ci
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/AwesomeProject.xcworkspace \
          -scheme AwesomeProject \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/AwesomeProject \
          CODE_SIGNING_ALLOWED=NO"
